# Generated by Django 5.1.1 on 2024-10-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description_ch',
            new_name='description_tr',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name_ch',
            new_name='movie_name_tr',
        ),
    ]
